Repository redacademy/quupe-spring-2018, pull requests merged in 2018-06, with the labels that each got.

#36 added packages to server and client and addded git ignore on server.
  quupe-RN/package.json
  quupe-RN/yarn.lock
  quupe-server/.gitignore
  quupe-server/package.json
  quupe-server/yarn.lock
Labels: Client, Project Setup, Server

#39 Integrated base folders and files in screens folder.
  quupe-RN/js/navigation/NavigationLayout.js
  quupe-RN/js/navigation/RootStackNavigator.js
  quupe-RN/js/navigation/config.js
  quupe-RN/js/navigation/styles.js
  quupe-RN/js/screens/Borrow/Borrow.js
  quupe-RN/js/screens/Borrow/BorrowContainer.js
  quupe-RN/js/screens/Borrow/index.js
  quupe-RN/js/screens/Borrow/styles.js
  quupe-RN/js/screens/Home/Home.js
  quupe-RN/js/screens/Home/HomeContainer.js
  quupe-RN/js/screens/Home/index.js
  quupe-RN/js/screens/Home/styles.js
  quupe-RN/js/screens/Lend/Lend.js
  quupe-RN/js/screens/Lend/LendContainer.js
  quupe-RN/js/screens/Lend/index.js
  quupe-RN/js/screens/Lend/styles.js
  quupe-RN/js/screens/Profile/Profile.js
  quupe-RN/js/screens/Profile/ProfileContainer.js
  quupe-RN/js/screens/Profile/index.js
  quupe-RN/js/screens/Profile/styles.js
  quupe-RN/js/screens/SignIn/SignIn.js
  quupe-RN/js/screens/SignIn/SignInContainer.js
  quupe-RN/js/screens/SignIn/index.js
  quupe-RN/js/screens/SignIn/styles.js
Labels: Client

#42 Added firebase to ios files and started roughing out containers/compo…
  quupe-RN/.gitignore
  quupe-RN/ios/GoogleService-Info.plist
  quupe-RN/ios/Podfile
  quupe-RN/ios/Podfile.lock
  quupe-RN/ios/quupe.xcodeproj/project.pbxproj
  quupe-RN/ios/quupe.xcworkspace/contents.xcworkspacedata
  quupe-RN/ios/quupe.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  quupe-RN/ios/quupe/AppDelegate.m
  quupe-RN/js/screens/SignIn/SignIn.js
  quupe-RN/js/screens/SignIn/SignInContainer.js
  quupe-RN/js/screens/SignIn/index.js
Labels: Client

#44 Added basic setup for Lend and borrow pages, as well as routing for l…
  quupe-RN/js/assets/index.js
  quupe-RN/js/assets/styles.js
  quupe-RN/js/navigation/NavigationLayout.js
  quupe-RN/js/navigation/RootStackNavigator.js
  quupe-RN/js/navigation/config.js
  quupe-RN/js/navigation/styles.js
  quupe-RN/js/screens/Borrow/Borrow.js
  quupe-RN/js/screens/Borrow/BorrowContainer.js
  quupe-RN/js/screens/Borrow/index.js
  quupe-RN/js/screens/Lend/Lend.js
  quupe-RN/js/screens/Lend/LendContainer.js
  quupe-RN/js/screens/Lend/index.js
Labels: Client, Project Setup

#58 Integrated base folders and files for additional screens and addition…
  quupe-RN/js/components/CategorySection/CategorySection.js
  quupe-RN/js/components/CategorySection/index.js
  quupe-RN/js/components/CategorySection/styles.js
  quupe-RN/js/components/PopularSection/PopularSection.js
  quupe-RN/js/components/PopularSection/index.js
  quupe-RN/js/components/PopularSection/styles.js
  quupe-RN/js/screens/BorrowedItems/BorrowedItems.js
  quupe-RN/js/screens/BorrowedItems/BorrowedItemsContainer.js
  quupe-RN/js/screens/BorrowedItems/index.js
  quupe-RN/js/screens/BorrowedItems/styles.js
  quupe-RN/js/screens/Category/Category.js
  quupe-RN/js/screens/Category/CategoryContainer.js
  quupe-RN/js/screens/Category/index.js
  quupe-RN/js/screens/Category/styles.js
  quupe-RN/js/screens/Favorites/Favorites.js
  quupe-RN/js/screens/Favorites/FavoritesContainer.js
  quupe-RN/js/screens/Favorites/index.js
  quupe-RN/js/screens/Favorites/styles.js
  quupe-RN/js/screens/LentItems/LentItems.js
  quupe-RN/js/screens/LentItems/LentItemsContainer.js
  quupe-RN/js/screens/LentItems/index.js
  quupe-RN/js/screens/LentItems/styles.js
  quupe-RN/js/screens/Messages/Messages.js
  quupe-RN/js/screens/Messages/MessagesContainer.js
  quupe-RN/js/screens/Messages/index.js
  quupe-RN/js/screens/Messages/styles.js
  quupe-RN/js/screens/MyItems/MyItems.js
  quupe-RN/js/screens/MyItems/MyItemsContainer.js
  quupe-RN/js/screens/MyItems/index.js
  quupe-RN/js/screens/MyItems/styles.js
  quupe-RN/js/screens/Popular/Popular.js
  quupe-RN/js/screens/Popular/PopularContainer.js
  quupe-RN/js/screens/Popular/index.js
  quupe-RN/js/screens/Popular/styles.js
  quupe-RN/js/screens/TransactionHistory/TransactionHistory.js
  quupe-RN/js/screens/TransactionHistory/TransactionHistoryContainer.js
  quupe-RN/js/screens/TransactionHistory/index.js
  quupe-RN/js/screens/TransactionHistory/styles.js
Labels: Client

#62 restructuring server.
  quupe-server/.graphcoolrc
  quupe-server/graphcool.yml
  quupe-server/src/authenticate.graphql
  quupe-server/src/authenticate.ts
  quupe-server/src/loggedInUser.graphql
  quupe-server/src/loggedInUser.ts
  quupe-server/src/signup.graphql
  quupe-server/src/signup.ts
  quupe-server/types.graphql
Labels: Project Setup, Server

#67 added apolloClient to client side and gql query working.Also added li…
  quupe-RN/js/App.js
  quupe-RN/js/config/apolloClient.js
  quupe-RN/js/screens/Home/HomeContainer.js
  quupe-RN/package.json
  quupe-RN/yarn.lock
  quupe-server/.eslintrc.json
  quupe-server/package.json
  quupe-server/yarn.lock
Labels: Client, Project Setup

#68 user auth working after graphql-lib updated.
  quupe-server/src/signup.ts
  quupe-server/types.graphql
Labels: Client, Server

#84 server schema added longitude and latitude. Mock data entered and spl…
  quupe-RN/android/app/build.gradle
  quupe-RN/android/app/src/main/java/com/quupe/MainApplication.java
  quupe-RN/android/settings.gradle
  quupe-RN/ios/Podfile
  quupe-RN/ios/quupe.xcodeproj/project.pbxproj
  quupe-RN/ios/quupe.xcodeproj/xcshareddata/xcschemes/quupe-tvOS.xcscheme
  quupe-RN/ios/quupe.xcodeproj/xcshareddata/xcschemes/quupe.xcscheme
  quupe-RN/ios/quupe/Base.lproj/LaunchScreen.xib
  quupe-RN/ios/quupe/Images.xcassets/Contents.json
  quupe-RN/ios/quupe/Images.xcassets/Splash Icon.imageset/Contents.json
  quupe-RN/ios/quupe/Images.xcassets/Splash Icon.imageset/qp_blue_org-1.png
  quupe-RN/ios/quupe/Images.xcassets/Splash Icon.imageset/qp_blue_org-2.png
  quupe-RN/ios/quupe/Images.xcassets/Splash Icon.imageset/qp_blue_org.png
  quupe-RN/ios/quupe/Info.plist
  quupe-RN/ios/quupeTests/Info.plist
  quupe-RN/js/App.js
  quupe-RN/js/assets/images/qp_blue_org.png
  quupe-RN/js/screens/Account/Account.js
  quupe-RN/package.json
  quupe-server/.graphcoolrc
  quupe-server/graphcool.yml
  quupe-server/src/signup.graphql
  quupe-server/src/signup.ts
  quupe-server/types.graphql
Labels: Client, Database

#88 Account page navigation working and account home page mostly styled. …
  .DS_Store
  quupe-RN/js/navigation/NavigationLayout.js
  quupe-RN/js/screens/Account/Account.js
  quupe-RN/js/screens/Account/AccountContainer.js
  quupe-RN/js/screens/Account/styles.js
  quupe-RN/js/screens/BorrowedItems/BorrowedItems.js
  quupe-RN/js/screens/BorrowedItems/BorrowedItemsContainer.js
  quupe-RN/js/screens/BorrowedItems/index.js
  quupe-RN/js/screens/Favorites/Favorites.js
  quupe-RN/js/screens/Favorites/FavoritesContainer.js
  quupe-RN/js/screens/Favorites/index.js
  quupe-RN/js/screens/LentItems/LentItems.js
  quupe-RN/js/screens/LentItems/LentItemsContainer.js
  quupe-RN/js/screens/LentItems/index.js
  quupe-RN/js/screens/Messages/Messages.js
  quupe-RN/js/screens/Messages/MessagesContainer.js
  quupe-RN/js/screens/Messages/index.js
  quupe-RN/js/screens/MyItems/MyItems.js
  quupe-RN/js/screens/MyItems/MyItemsContainer.js
  quupe-RN/js/screens/MyItems/index.js
  quupe-RN/js/screens/TransactionHistory/TransactionHistory.js
  quupe-RN/js/screens/TransactionHistory/TransactionHistoryContainer.js
  quupe-RN/js/screens/TransactionHistory/index.js
  quupe-server/types.graphql
Labels: Client

#95 Account page styled and items page styled. Items page still needs rou…
  quupe-RN/js/screens/Account/Account.js
  quupe-RN/js/screens/Account/AccountContainer.js
  quupe-RN/js/screens/Account/styles.js
  quupe-RN/js/screens/MyItems/MyItems.js
  quupe-RN/js/screens/MyItems/MyItemsContainer.js
  quupe-RN/js/screens/MyItems/styles.js
Labels: Client

#101 borrowedItems, lentItems, myItems now obtaining all proper items acco…
  quupe-RN/js/navigation/NavigationLayout.js
  quupe-RN/js/screens/Account/Account.js
  quupe-RN/js/screens/Account/AccountContainer.js
  quupe-RN/js/screens/Account/styles.js
  quupe-RN/js/screens/BorrowedItems/BorrowedItems.js
  quupe-RN/js/screens/BorrowedItems/BorrowedItemsContainer.js
  quupe-RN/js/screens/BorrowedItems/styles.js
  quupe-RN/js/screens/LentItems/LentItems.js
  quupe-RN/js/screens/LentItems/LentItemsContainer.js
  quupe-RN/js/screens/MyItems/MyItemsContainer.js
  quupe-server/types.graphql
Labels: Client
